### ISSUE TITLE
[BUG] `Item:MimeType` seems invalid

### ISSUE THREAD

**Issue by AlexV525** [ente-io/motion_photo#4]
https://developer.android.com/media/platform/motion-photo-format#item_element

In the official doc of Motion Photo, there is only **Mime** attribute, not **MimeType**.

https://github.com/ente-io/motion_photos/blob/f1ec3d35d5cee2ec1c098b5ca276f311a96d800a/lib/src/constants.dart#L13

**Comment by ua741** [comment]
Thank you for pointing this issue.
Surprisingly, in our current samples, we have never encountered a case where we needed to look up this attribute, as most of the motion photo samples were detected in the previous steps.
